# 线上配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/yupi
    username: root
    password: Lovelzx629916.
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0